version: "3.7"

services:
  nethermind:
    container_name: nethermind
    image: nethermind/nethermind:${EXECUTION_LAYER_VERSION}
    restart: always
    hostname: nethermind
    command:
      - --JsonRpc.Enabled=true
      - --JsonRpc.EnabledModules=["Eth","Subscribe","Trace","TxPool","Web3","Personal","Proof","Net","Parity","Health"]
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8545
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8551
      - --JsonRpc.JwtSecretFile=/auth/jwt.hex
      - --HealthChecks.Enabled=true
      - --HealthChecks.WebhooksEnabled=false
      - --HealthChecks.UIEnabled=false
      - --HealthChecks.PollingInterval=10
      #- --config ${TARGET_CHAIN}
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 127.0.0.1:8551:8551
      - 127.0.0.1:8545:8545
    volumes:
      - ./auth:/auth
      - ${DOCKER_VOL_PATH}/nethermind/db:/nethermind/nethermind_db
      - ${DOCKER_VOL_PATH}/nethermind/logs:/nethermind/logs
      - ${DOCKER_VOL_PATH}/nethermind/keystore:/nethermind/keystore
      - ${DOCKER_VOL_PATH}/nethermind/data:/nethermind/data

  beacon:
    container_name: beacon
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${CONSENSUS_LAYER_VERSION}
    restart: always
    hostname: beacon
    depends_on:
      - nethermind
    command:
      - --verbosity=debug
      - --slasher
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
      - --monitoring-host=0.0.0.0
      - --execution-endpoint=http://nethermind:8551
      - --jwt-secret=/auth/jwt.hex
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --p2p-host-ip=${PUBLIC_IP}
      #- --genesis-state=/genesis/${ETH_NETWORK}/genesis.ssz
      - --checkpoint-sync-url=${BEACON_CHECKPOINT_URL}
      - --genesis-beacon-api-url=${BEACON_CHECKPOINT_URL}
      - --accept-terms-of-use
      - --${ETH_NETWORK}
    ports:
      - 3500:3500/tcp
      - 127.0.0.1:4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - ./auth:/auth
      #- ./beacon-chain-genesis:/genesis
      - ${DOCKER_VOL_PATH}/beacon:/data

  validator:
    container_name: validator
    image: gcr.io/prysmaticlabs/prysm/validator:${CONSENSUS_LAYER_VERSION}
    restart: on-failure
    hostname: validator
    network_mode: host
    depends_on:
      - beacon
    command:
      - --beacon-rpc-provider=beacon:4000
      - --wallet-dir=/data/wallets
      - --datadir=/data/db
      - --monitoring-host=0.0.0.0
      - --accept-terms-of-use
      - --wallet-password-file=/launchpad/wallet-password
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --${ETH_NETWORK}
    volumes:
      - ./auth:/auth
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data
