version: "3.7"

services:
  validator-import-launchpad:
    container_name: validator-import-launchpad
    image: gcr.io/prysmaticlabs/prysm/validator:${CONSENSUS_LAYER_VERSION}
    command:
      - accounts
      - import
      - --keys-dir=/launchpad/validator_keys
      - --wallet-dir=/data/wallets
      - --wallet-password-file=/launchpad/wallet-password
      - --accept-terms-of-use
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data

  validator-list-accounts:
    container_name: validator-list-accounts
    image: gcr.io/prysmaticlabs/prysm/validator:${CONSENSUS_LAYER_VERSION}
    command:
      - accounts
      - list
      - --wallet-dir=/data/wallets
      - --wallet-password-file=/launchpad/wallet-password
      - --accept-terms-of-use
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data

  validator-exit:
    container_name: validator-exit
    image: gcr.io/prysmaticlabs/prysm/cmd/prysmctl:${CONSENSUS_LAYER_CMD_VERSION}
    command:
      - validator
      - exit
      - --wallet-dir=/data/wallets
      - --wallet-password-file=/launchpad/wallet-password
      - --public-keys=${PUB_KEY}
      - --accept-terms-of-use
      - --beacon-rpc-provider=beacon:4000
      - --force-exit
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data
