version: "3.7"

services:
  validator-import-launchpad:
    container_name: validator-import-launchpad
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION}
    command:
      - accounts
      - import
      - --keys-dir="/launchpad/validator_keys"
      - --wallet-dir="/data/wallets"
      - --wallet-password-file="/launchpad/wallet-password"
      - --accept-terms-of-use
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data

  validator-list-accounts:
    container_name: validator_list_accounts
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION}
    command:
      - accounts
      - list
      - --wallet-dir="/data/wallets"
      - --wallet-password-file="/launchpad/wallet-password"
      - --accept-terms-of-use
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data

  validator-exit:
    container_name: validator-exit
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION}
    command:
      - accounts
      - voluntary-exit
      - --wallet-dir="/data/wallets"
      - --wallet-password-file="/launchpad/wallet-password"
      - --public-keys=${PUBKEY}
      - --accept-terms-of-use
      - --beacon-rpc-provider=beacon:4000
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data

  validator-delete-account:
    container_name: validator-delete-account
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_VERSION}
    command:
      - accounts
      - delete
      - --wallet-dir=/data/wallets
      - --wallet-password-file="/launchpad/wallet-password"
      - --accept-terms-of-use
      - --${ETH_NETWORK}
    volumes:
      - ./launchpad:/launchpad
      - ${DOCKER_VOL_PATH}/validator:/data
